# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runstepsif

name: "Gitcord"
description: "expand GitHub into Discord"

inputs:
  github-event-name:
    description: "GitHub event name used as $GITHUB_EVENT_NAME"
    requried: true
  github-event-payload:
    description: "GitHub event payload JSON used as $GITHUB_EVENT_PAYLOAD"
    required: true
  github-token:
    description: "GitHub token used as $GITHUB_TOKEN"
    required: true
  discord-token:
    description: "Discord token used as $DISCORD_TOKEN"
    required: true
  discord-channel-id:
    description: "Discord channel ID used as $DISCORD_CHANNEL_ID"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.19"

    - name: Install Gitcord
      shell: bash
      run: echo $GITHUB_ACTIONS_REF && go install github.com/ethanthatonekid/gitcord@$GITHUB_ACTIONS_REF
      env:
        GITHUB_ACTIONS_REF: "${{ github.event.workflow_run.head_sha }}"

    - name: Run Gitcord for GitHub event
      shell: bash
      run: echo $GITHUB_ACTIONS_REF && gitcord
      env:
        GITHUB_TOKEN: "${{ inputs.github-token }}"
        GITHUB_EVENT_NAME: ${{ inputs.github-event-name }}
        GITHUB_EVENT_PAYLOAD: ${{ inputs.github-event-payload }}
        DISCORD_TOKEN: "${{ inputs.discord-token }}"
        DISCORD_CHANNEL_ID: "${{ inputs.discord-channel-id }}"
