# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runstepsif

name: "Gitcord"
description: "expand GitHub into Discord"

inputs:
  payload:
    description: "GitHub event payload passed into Gitcord stdin"
    required: true
  github-token:
    description: "GitHub token"
    required: true
  discord-token:
    description: "Discord token"
    required: true
  discord-channel-id:
    description: "Discord channel ID"
    required: true

runs:
  using: "composite"
  steps:
    - name: Validate GitHub event payload
      id: event_payload
      shell: bash
      env:
        p: ${{ inputs.payload }}
      run: |
        if [[ -z "${{ inputs.payload }}" ]]; then
          echo "Gitcord: GitHub event payload is empty"
          exit 1
        fi

        # See:
        # https://github.com/mkungla/actions-set-text-output/blob/414dd008c8ad6a77fb0fe56e62076111ca59132b/action.yml
        p="${p//'%'/'%25'}"
        p="${p//$'\n'/'%0A'}"
        p="${p//$'\r'/'%0D'}"
        echo "::set-output name=payload::$p"

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.19"

    - name: Gitcord
      shell: bash
      run: |
        go install github.com/ethanthatonekid/gitcord@latest
        echo "${{ steps.event_payload.outputs.payload }}" | gitcord
      env:
        GITHUB_TOKEN: "${{ inputs.github-token }}"
        DISCORD_TOKEN: "${{ inputs.discord-token }}"
        DISCORD_CHANNEL_ID: "${{ inputs.discord-channel-id }}"
