# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runstepsif

name: "Gitcord"
description: "expand GitHub into Discord"

inputs:
  payload:
    description: "GitHub event payload passed into Gitcord stdin"
    required: true
  github-token:
    description: "GitHub token"
    required: true
  discord-token:
    description: "Discord token"
    required: true
  discord-channel-id:
    description: "Discord channel ID"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.19"

    # See:
    # https://github.com/mkungla/actions-set-text-output/blob/414dd008c8ad6a77fb0fe56e62076111ca59132b/action.yml
    - name: Gitcord
      shell: bash
      run: |
        PAYLOAD="${PAYLOAD//'%'/'%25'}"
        PAYLOAD="${PAYLOAD//$'\n'/'%0A'}"
        PAYLOAD="${PAYLOAD//$'\r'/'%0D'}"

        go install github.com/ethanthatonekid/gitcord@latest
        echo "${{ $PAYLOAD }}" | gitcord
      env:
        PAYLOAD: ${{ inputs.payload }}
        GITHUB_TOKEN: "${{ inputs.github-token }}"
        DISCORD_TOKEN: "${{ inputs.discord-token }}"
        DISCORD_CHANNEL_ID: "${{ inputs.discord-channel-id }}"
