# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runstepsif

name: "Gitcord"
description: "expand GitHub into Discord"

runs:
  using: "composite"
  steps:
    - name: Setup Go
      uses: actions/setup-go@v3

    - name: Gitcord
      shell: bash
      run: |
        go install github.com/ethanthatonekid/gitcord
        echo "$GITHUB_EVENT_PAYLOAD" | gitcord
      env:
        GITHUB_REPO: "${{ github.event.repository.name }}"
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        DISCORD_CHANNEL_ID: "${{ secrets.DISCORD_CHANEL_ID }}"
        DISCORD_GUILD_ID: "${{ secrets.DISCORD_GUILD_ID }}"
        DISCORD_TOKEN: "${{ secrets.DISCORD_TOKEN }}"
