# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runstepsif

name: "Gitcord"
description: "expand GitHub into Discord"

inputs:
  GITHUB_EVENT_PAYLOAD:
    description: "GITHUB_EVENT_PAYLOAD expected in stdin by gitcord"
    default: ${{ $GITHUB_EVENT_PAYLOAD }}

runs:
  using: "composite"
  steps:
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.19"

    - name: Gitcord
      shell: bash
      run: |
        go install github.com/ethanthatonekid/gitcord@latest
        echo "Yo!: ${{ $GITHUB_EVENT_PAYLOAD }}"
        echo "${{ $GITHUB_EVENT_PAYLOAD }}" | gitcord
