# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runstepsif

name: "Gitcord"
description: "expand GitHub into Discord"

inputs:
  PAYLOAD:
    description: "GitHub event payload passed into gitcord stdin"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.19"

    - name: Gitcord
      shell: bash
      run: |
        go install github.com/ethanthatonekid/gitcord@latest
        echo "Yo!: ${{ inputs.PAYLOAD }}"
        echo "${{ inputs.PAYLOAD }}" | gitcord
