name: Gitcord

on:
  issues:
    types: [opened, reopened, closed, deleted, transferred]
  pull_request:
    types: [opened, reopened, closed, deleted, ready_for_review]
  issue_comment:
    types: [created, edited]
  pull_request_review:
    types: [submitted]

jobs:
  gitcord:
    runs-on: ubuntu-latest
    steps:
      - uses: .
        env:
          GITHUB_REPO: ${{ github.event.repository.name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANEL_ID }}
          DISCORD_GUILD_ID: ${{ secrets.DISCORD_GUILD_ID }}
