name: Gitcord

on:
  issues:
    types:
      [
        opened,
        edited,
        deleted,
        transferred,
        closed,
        reopened,
        assigned,
        unassigned,
        labeled,
        unlabeled,
        locked,
        unlocked,
        milestoned,
        demilestoned,
      ]
  issue_comment:
    types: [created, edited, deleted]
  pull_request:
    types:
      [
        opened,
        edited,
        deleted,
        transferred,
        review_requested,
        review_request_removed,
        ready_for_review,
        closed,
        reopened,
        assigned,
        unassigned,
        labeled,
        unlabeled,
        locked,
        unlocked,
        milestoned,
        demilestoned,
      ]
  pull_request_review:
    types: [submitted, edited, dismissed]
  pull_request_review_comment:
    types: [created, edited, deleted]

jobs:
  gitcord:
    runs-on: ubuntu-latest
    steps:
      - name: "Gitcord ${{ github.event_name }}:${{ github.event.action }} (${{ github.event.repository.name }})"
        uses: ethanthatonekid/gitcord@v1-beta
        with:
          PAYLOAD: "${{ github.event }}"
        env:
          GITHUB_TOKEN: "${{ github.TOKEN }}"
          DISCORD_TOKEN: "${{ secrets.DISCORD_TOKEN }}"
          DISCORD_CHANNEL_ID: "${{ secrets.DISCORD_CHANNEL_ID }}"
