name: Gitcord

on:
  issues:
    types: [opened, edited, deleted, transferred, closed, reopened, assigned, unassigned, labeled, unlabeled, locked, unlocked, milestoned, demilestoned]
  issue_comment:
    types: [created, edited, deleted]
  pull_request:
    types: [opened, edited, deleted, transferred, review_requested, review_request_removed, ready_for_review, closed, reopened, assigned, unassigned, labeled, unlabeled, locked, unlocked, milestoned, demilestoned]
  pull_request_review:
    types: [submitted, edited, dismissed]
  pull_request_review_comment:
    types: [created, edited, deleted]
  # pull_request_review_thread:
  #   types: [created, updated, resolved, unresolved]

jobs:
  gitcord:
    runs-on: ubuntu-latest
    steps:
      - uses: .
        env:
          GITHUB_REPO: ${{ github.event.repository.name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANEL_ID }}
          DISCORD_GUILD_ID: ${{ secrets.DISCORD_GUILD_ID }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
